2024-09-23 16:28:38,881 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 16:28:49,424 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 16:36:02,225 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:06:16,709 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:07:53,449 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:07:58,604 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:08:08,352 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:39:49,192 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:42:33,662 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:44:35,724 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:44:38,650 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:44:47,457 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:45:06,300 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:46:26,103 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:46:28,770 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:46:30,525 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:48:34,476 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:51:01,529 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:51:33,769 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:52:55,371 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:55:42,771 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 17:59:32,291 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:00:06,818 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:02:06,027 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:03:30,722 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:03:36,164 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:03:37,902 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP ARC 211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:08:07,858 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:11:39,560 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-09-23 18:12:41,298 ERROR    Uncaught exception: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 977, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 732, in test_project
    project.build()
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 690, in build
    p.build(clear)
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 641, in build
    run_command(['make'])
  File "C:\Users\kimjazoku\Documents\JakeKim\RUTGERS\Fall 2024\COMP_ARC_211\HOMEWORK\pa1\autograde.py", line 40, in run_command
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kimjazoku\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
